import './globals.css';

export const metadata = {
  title: "my-app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className="my-app">
        {children}
      </body>
    </html>
  );
}
