import '@/globals.css';

export const metadata = {
  title: 'jw app',
  // charset: 'utf-8',
  description: 'jw app Generated by create next app',
  formatDetection: {
    email: false,
    address: false,
    telephone: false
  }
};

export const viewport = {
  width: 'device-width',
  initialScale: 1.0,
  maximumScale: 1.0,
  userScalable: false,
  viewportFit: 'cover'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
